- name: install nginx repo
  become: yes
  become_method: sudo
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  become: yes
  become_method: sudo
  yum: name=nginx state=installed

- name: ensure nginx/conf.d is empty
  become: yes
  become_method: sudo
  file: path=/etc/nginx/conf.d/ state=absent

- name: create nginx/conf.d directory
  become: yes
  become_method: sudo
  file: path=/etc/nginx/conf.d state=directory

- name: place nginx conf file
  become: yes
  become_method: sudo
  copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: place nginx conf file for app
  become: yes
  become_method: sudo
  template: src=templates/app.conf.j2 dest=/etc/nginx/conf.d/app.conf
  notify: restart nginx

- name: set auto start
  become: yes
  become_method: sudo
  shell: chkconfig nginx on
